### ISSUE TITLE
Move list of file extensions to a seperate file

### ISSUE THREAD

**Issue by shivrm** [ANIRUDH-GHUB/file-organiser#3]
The list of file extensions is currently stored as a `dict` in the `extension.py` file. Instead of this, it can be placed in a seperate `extensions.json` file and loaded with the `json` library.

eg.
```py
import json

with open('extensions.json') as f:
    data = json.load(f)
```

**Comment by ANIRUDH-GHUB** [comment]
Great Observation.
It would be great if you can raise a PR with that changes.

**Comment by shivrm** [comment]
Done! #5
